version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: torii-nihongo-gakuin_container
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:nhatngutorii@torii-nihongo-db.ct64ww6csug1.ap-southeast-1.rds.amazonaws.com:5432/postgres?schema=public
      - ACCESS_TOKEN_SECRET=nhatngutorii
      - ACCESS_TOKEN_EXPIRES_IN=1h
      - REFRESH_TOKEN_SECRET=nhatngutorii
      - REFRESH_TOKEN_EXPIRES_IN=1d
      - PORT=4000
      - SECRET_API_KEY=toriinihongogakuin
      - PAYMENT_API_KEY=
      - ADMIN_NAME=
      - ADMIN_PASSWORD=
      - ADMIN_EMAIL=
      - ADMIN_PHONE_NUMBER=
      - OTP_EXPIRES_IN=5m
      - RESEND_API_KEY=re_XDGkQ5ic_CziF5XzBiXYxAnnoPoJgFDpz
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_REDIRECT_URI=
      - GOOGLE_CLIENT_REDIRECT_URI=
      - APP_NAME=
      - S3_REGION=ap-southeast-1
      - S3_ACCESS_KEY=AKIAVVZPCSCKZAVMUOVN
      - S3_SECRET_KEY=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
      - S3_BUCKET_NAME=torii-nihongo-gakuin-s3
      - REDIS_URL=redis://default:password@localhost:6379
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:4000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
