export const NotificationType = {
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
  COURSE_ENROLLMENT: 'COURSE_ENROLLMENT',
  COURSE_UPDATE: 'COURSE_UPDATE',
  MESSAGE: 'MESSAGE',
  MENTION: 'MENTION',
  LIKE: 'LIKE',
  COMMENT: 'COMMENT',
  RATING: 'RATING',
  SYSTEM: 'SYSTEM',
  PROMOTION: 'PROMOTION',
  REMINDER: 'REMINDER',
}

export const NotificationStatus = {
  UNREAD: 'UNREAD',
  READ: 'READ',
  ARCHIVED: 'ARCHIVED',
}

export const NotificationPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
}
